language: generic

install:
  - nvm use 11.0.0
  - npm --version
  - node --version
  - ./gradlew build
  - git clone https://github.com/kahverengi001/portfolio.git portfolio-front-end
  - cd portfolio-front-end
  - npm install
  - npm run build
  - ls -a
  - ls ..
  - cp -avr public ../public
  - cd ..
  - rm -rf portfolio-front-end
  - ls -a
  - ls -a public

deploy:
  provider: heroku
  cleanup: false
  api_key: $HEROKU_API_KEY
  strategy: api
  app: kahverengi-portfolio
  on:
    branch: master